## Importing pandas

### Bắt đầu và kiểm tra thiết lập pandas của bạn

Mức độ: *easy* 

**1.** Import pandas dưới bí danh `pd`.

In [31]:
import pandas as pd

Ba câu tiếp theo khó hơn một chút.


**26.** Trong ô bên dưới, bạn có một DataFrame `df` bao gồm 10 cột số dấu phẩy động. Chính xác 5 mục trong mỗi hàng là giá trị NaN.

Đối với mỗi hàng của DataFrame, hãy tìm *cột* chứa giá trị NaN *thứ ba*.

Bạn nên trả về một Chuỗi nhãn cột: `e, c, d, h, d`

In [32]:
import numpy as np
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

nan_pos = df.isna().cumsum(axis=1)  # Đếm số NaN tích lũy theo từng hàng
third_nan_cols = nan_pos.eq(3).idxmax(axis=1)  # Tìm cột đầu tiên có tổng bằng 3

print(third_nan_cols.tolist())  # ['e', 'c', 'd', 'h', 'd']


['e', 'c', 'd', 'h', 'd']


**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals': 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [33]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

result = df.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum())
print(result)

grps
a    409
b    156
c    345
Name: vals, dtype: int64


**28.** DataFrame `df` được xây dựng bên dưới có hai cột số nguyên 'A' và 'B'. Các giá trị trong 'A' nằm trong khoảng từ 1 đến 100 (bao gồm). 

Đối với mỗi nhóm 10 số nguyên liên tiếp trong 'A' (tức là `(0, 10]`, `(10, 20]`, ...), hãy tính tổng các giá trị tương ứng trong cột 'B'.

Câu trả lời sẽ là một Series như sau:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [34]:
import pandas as pd
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

bins = np.arange(0, 101, 10)  
labels = [(bins[i], bins[i+1]) for i in range(len(bins)-1)]  

df['A_bins'] = pd.cut(df['A'], bins=bins, labels=labels, include_lowest=True, right=True)
result = df.groupby('A_bins')['B'].sum()

print(result)

A_bins
(0, 10)      635
(10, 20)     360
(20, 30)     315
(30, 40)     306
(40, 50)     750
(50, 60)     284
(60, 70)     424
(70, 80)     526
(80, 90)     835
(90, 100)    852
Name: B, dtype: int32


C:\Users\tanye\AppData\Local\Temp\ipykernel_9348\1381039253.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby('A_bins')['B'].sum()


## DataFrames: những vấn đề khó hơn 

### Những điều này có thể đòi hỏi một chút suy nghĩ vượt ra ngoài khuôn khổ...

...nhưng tất cả đều có thể giải quyết được chỉ bằng các phương pháp pandas/NumPy thông thường (và do đó tránh sử dụng vòng lặp `for` rõ ràng)..

Mức độ: *hard*

**29.** Hãy xem xét DataFrame `df` trong đó có một cột số nguyên 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
Đối với mỗi giá trị, hãy đếm ngược lại sự khác biệt đến số không trước đó (hoặc thời điểm bắt đầu của Series, tùy theo giá trị nào gần hơn). Do đó, các giá trị này phải là

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Tạo cột mới này thành cột 'Y'.

In [35]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
df['Y'] = (df['X'] != 0).cumsum() - (df['X'] != 0).cumsum().where(df['X'] == 0).ffill().fillna(0).astype(int)
print(df)

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2


**30.** Hãy xem xét DataFrame được xây dựng bên dưới chứa các hàng và cột dữ liệu số. 

Tạo danh sách các vị trí chỉ mục hàng-cột của 3 giá trị lớn nhất trong DataFrame này. Trong trường hợp này, câu trả lời sẽ là:
```
[(5, 7), (6, 4), (2, 5)]
```

In [36]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
indices = np.unravel_index(np.argsort(df.values.ravel())[-3:], df.shape)
top_3_indices = list(zip(indices[0], indices[1]))
print(top_3_indices)

[(7, 5), (4, 6), (5, 2)]


**31.** Bạn được cung cấp DataFrame bên dưới với một cột ID nhóm, 'grps', và một cột chứa các giá trị số nguyên tương ứng, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Tạo một cột mới 'patched_values' chứa các giá trị giống như 'vals' bất kỳ giá trị âm nào trong 'vals' với nhóm mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [37]:
import pandas as pd
import numpy as np

df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

mean_vals = df[df["vals"] >= 0].groupby("grps")["vals"].mean()

df["patched_vals"] = df.apply(lambda row: mean_vals[row["grps"]] if row["vals"] < 0 else row["vals"], axis=1)

print(df)


    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6


**32.** Triển khai giá trị trung bình lăn trên các nhóm có kích thước cửa sổ là 3, bỏ qua giá trị NaN. Ví dụ, hãy xem xét DataFrame sau:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
Mục tiêu là tính toán Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. cửa sổ đầu tiên có kích thước ba cho nhóm 'b' có các giá trị 3.0, NaN và 3.0 và xuất hiện ở chỉ mục hàng 5. Thay vì là NaN, giá trị trong cột mới ở chỉ mục hàng này phải là 3.0 (chỉ sử dụng hai giá trị không phải NaN để tính giá trị trung bình (3+3)/2)

In [38]:
df = pd.DataFrame({'group': list('aabbabbbabab'),
                   'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
df['rolling_mean'] = df.groupby('group')['value'].transform(lambda x: x.rolling(3, min_periods=1).mean())

print(df)

   group  value  rolling_mean
0      a    1.0      1.000000
1      a    2.0      1.500000
2      b    3.0      3.000000
3      b    NaN      3.000000
4      a    2.0      1.666667
5      b    3.0      3.000000
6      b    NaN      3.000000
7      b    1.0      2.000000
8      a    7.0      3.666667
9      b    3.0      2.000000
10     a    NaN      4.500000
11     b    8.0      4.000000


## Series and DatetimeIndex

### Bài tập tạo và thao tác Series với dữ liệu ngày giờ

Mức độ: *easy/medium*

pandas rất tuyệt vời để làm việc với ngày tháng và thời gian. Những câu đố này khám phá một số chức năng này.


**33.** Tạo một DatetimeIndex chứa mỗi ngày làm việc của năm 2015 và sử dụng nó để lập chỉ mục cho một Series số ngẫu nhiên. Chúng ta hãy gọi Series này là `s`.

In [39]:
dates = pd.date_range('2015-01-01', '2015-12-31', freq='B')
s = pd.Series(1, index=dates)
print(s)

2015-01-01    1
2015-01-02    1
2015-01-05    1
2015-01-06    1
2015-01-07    1
             ..
2015-12-25    1
2015-12-28    1
2015-12-29    1
2015-12-30    1
2015-12-31    1
Freq: B, Length: 261, dtype: int64


**34.** Tìm tổng các giá trị trong `s` của mỗi thứ Wednesday.

In [40]:
wednesday_sum = s[s.index.weekday == 2].sum()
print(wednesday_sum)

52


**35.** Đối với mỗi tháng dương lịch trong `s`, hãy tìm giá trị trung bình.

In [41]:
monthly_avg = s.resample('M').mean()
print(monthly_avg)

2015-01-31    1.0
2015-02-28    1.0
2015-03-31    1.0
2015-04-30    1.0
2015-05-31    1.0
2015-06-30    1.0
2015-07-31    1.0
2015-08-31    1.0
2015-09-30    1.0
2015-10-31    1.0
2015-11-30    1.0
2015-12-31    1.0
Freq: ME, dtype: float64


C:\Users\tanye\AppData\Local\Temp\ipykernel_9348\117926256.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_avg = s.resample('M').mean()


**36.**Đối với mỗi nhóm bốn tháng liên tiếp trong lịch `s`, hãy tìm ngày có giá trị cao nhất.

In [42]:
four_month_max = s.resample('4M').apply(lambda x: x.idxmax())
print(four_month_max)

2015-01-31   2015-01-01
2015-05-31   2015-02-02
2015-09-30   2015-06-01
2016-01-31   2015-10-01
Freq: 4ME, dtype: datetime64[ns]


C:\Users\tanye\AppData\Local\Temp\ipykernel_9348\158340565.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  four_month_max = s.resample('4M').apply(lambda x: x.idxmax())


**37.** Tạo DateTimeIndex bao gồm thứ Năm tuần thứ ba của mỗi tháng trong các năm 2015 và 2016.

In [43]:
third_thursdays = pd.date_range('2015-01-01', '2016-12-31', freq='WOM-3THU')
print(third_thursdays)

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq='WOM-3THU')


## Làm sạch dữ liệu

### Làm cho DataFrame dễ làm việc hơn

Mức độ: *easy/medium*

Điều này xảy ra thường xuyên: ai đó cung cấp cho bạn dữ liệu chứa chuỗi string không đúng định dạng, Python, danh sách và dữ liệu bị thiếu. Làm thế nào để bạn sắp xếp chúng để có thể tiếp tục phân tích?

Hãy coi cái được cung cấp này như DataFrame để sử dụng trong các câu sau:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
Được định dạng, nó trông như thế này:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(Đây là một số dữ liệu chuyến bay do tác giả bịa ra; nó không có mục đích chính xác theo bất kỳ cách nào.)


**38.** Một số giá trị trong cột **FlightNumber** bị thiếu (chúng là `NaN`). Những con số này có nghĩa là tăng thêm 10 với mỗi hàng nên cần phải đặt 10055 và 10075 vào vị trí. Sửa đổi `df` để điền vào những con số bị thiếu này và biến cột thành một cột số nguyên (thay vì một cột số thực).

In [44]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
                   'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)
print(df)


            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"


**39.** Cột **From\_To** sẽ tốt hơn nếu là hai cột riêng biệt! Tách từng chuỗi trên dấu gạch dưới `_` để tạo một DataFrame tạm thời mới có tên là 'temp' với các giá trị chính xác. Gán tên cột chính xác 'From' và 'To' cho DataFrame tạm thời này.

In [45]:
temp = df['From_To'].str.split('_', expand=True).rename(columns={0: 'From', 1: 'To'})
print(temp)

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn


**40.** Lưu ý cách viết hoa tên thành phố được trộn lẫn trong DataFrame tạm thời này 'temp'. Chuẩn hóa các chuỗi sao cho chỉ có chữ cái đầu tiên là chữ hoa (ví dụ: "londON" sẽ trở thành "London".)

In [46]:
temp = temp.apply(lambda x: x.str.capitalize())
print(temp)

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


**41.** Xóa cột **From_To** khỏi `df` và đính kèm DataFrame tạm thời 'temp' từ các câu hỏi trước đó.

In [47]:
df = df.drop(['From_To', 'From', 'To'], axis=1, errors='ignore').join(temp)
print(df)

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London


**42**. Trong cột **Airline**, bạn có thể thấy một số dấu câu và ký hiệu bổ sung xuất hiện xung quanh tên hãng hàng không. Thực hiện chính xác hóa tên hãng hàng không. Ví dụ: `'(British Airways. )'` phải trở thành `'British Airways'`.

In [48]:
df['Airline'] = df['Airline'].astype(str).str.extract(r'([a-zA-Z\s]+)')[0].str.strip()
print(df)

   FlightNumber  RecentDelays          Airline      From         To
0         10045      [23, 47]              KLM    London      Paris
1         10055            []       Air France    Madrid      Milan
2         10065  [24, 43, 87]  British Airways    London  Stockholm
3         10075          [13]       Air France  Budapest      Paris
4         10085      [67, 32]        Swiss Air  Brussels     London


**43**. Trong cột RecentDelays, các giá trị đã được nhập vào DataFrame dưới dạng danh sách. Chúng tôi muốn mỗi giá trị đầu tiên trong cột riêng của nó, mỗi giá trị thứ hai trong cột riêng của nó, v.v. Nếu không có giá trị thứ N, giá trị sẽ là NaN.

Mở rộng Series của các danh sách thành một DataFrame có tên là `delays`, đổi tên các cột `delay_1`, `delay_2`, v.v. và thay thế cột RecentDelays không mong muốn trong `df` bằng `delays`.

In [49]:
if 'RecentDelays' in df.columns:
    delays = df['RecentDelays'].apply(pd.Series)
    delays.columns = ['delay_' + str(i+1) for i in range(delays.shape[1])]
    df = df.drop('RecentDelays', axis=1).join(delays)
else:
    print("Cột 'RecentDelays' không tồn tại trong DataFrame!")

print(df)

   FlightNumber          Airline      From         To  delay_1  delay_2  \
0         10045              KLM    London      Paris     23.0     47.0   
1         10055       Air France    Madrid      Milan      NaN      NaN   
2         10065  British Airways    London  Stockholm     24.0     43.0   
3         10075       Air France  Budapest      Paris     13.0      NaN   
4         10085        Swiss Air  Brussels     London     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN  


Bây giờ DataFrame sẽ trông đẹp hơn nhiều.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

## Sử dụng MultiIndexes

### Vượt ra ngoài DataFrames phẳng với các cấp chỉ mục bổ sung

Mức độ: *medium*

Các bài tập trước đây đã cho chúng ta thấy việc phân tích dữ liệu từ DataFrames được trang bị một mức chỉ mục duy nhất. Tuy nhiên, pandas cũng cung cấp cho bạn khả năng lập chỉ mục dữ liệu của mình bằng cách sử dụng *multiple* mức. Điều này rất giống với việc thêm các chiều mới vào một Series hoặc một DataFrame. Ví dụ, một Series là 1D, nhưng bằng cách sử dụng MultiIndex với 2 mức, chúng ta có được chức năng tương tự như một DataFrame 2D.

Bộ câu hỏi dưới đây khám phá cách bạn có thể sử dụng nhiều cấp chỉ mục để nâng cao khả năng phân tích dữ liệu.

Để khởi động, chúng ta sẽ xem xét một Series có hai mức chỉ số.

**44**. Với các danh sách `letters = ['A', 'B', 'C']` và `numbers = list(range(10))`, hãy xây dựng một đối tượng MultiIndex từ tích của hai danh sách. Sử dụng nó để lập chỉ mục cho một Series các số ngẫu nhiên. Gọi Series này là `s`.

In [50]:
tuples = pd.MultiIndex.from_product([['A', 'B', 'C'], range(10)])
s = pd.Series(np.random.randn(len(tuples)), index=tuples)
print (s)

A  0   -0.113967
   1   -0.699651
   2   -0.811594
   3    0.694270
   4   -0.645175
   5    0.610877
   6    1.035288
   7   -0.988185
   8    0.384448
   9   -1.183955
B  0   -0.498954
   1   -0.579669
   2   -1.282645
   3    1.183657
   4    0.180360
   5   -0.120949
   6    1.307612
   7    0.202408
   8   -0.506307
   9    0.624723
C  0    0.530930
   1   -2.178226
   2    0.351061
   3    0.487015
   4    0.022994
   5    2.260423
   6    0.701160
   7    1.351438
   8   -1.288183
   9   -0.197429
dtype: float64


**45.** Kiểm tra xem chỉ mục của `s` có được sắp xếp theo thứ tự từ điển hay không (đây là thuộc tính cần thiết để lập chỉ mục hoạt động chính xác với MultiIndex).

In [51]:
sorted_index = s.index.is_monotonic_increasing 
print(sorted_index)

True


**46**. Chọn các nhãn `1`, `3` và `6` từ cấp độ thứ hai của MultiIndexed Series.

In [52]:
s_level_1 = s.loc[(slice(None), [1, 3, 6])]
print(s_level_1)

A  1   -0.699651
   3    0.694270
   6    1.035288
B  1   -0.579669
   3    1.183657
   6    1.307612
C  1   -2.178226
   3    0.487015
   6    0.701160
dtype: float64


**47**. Cắt các Series `s`; cắt đến nhãn 'B' cho cấp độ đầu tiên và từ nhãn 5 trở đi cho cấp độ thứ hai.

In [53]:
sliced_s = s.loc['B':, 5:]
print(sliced_s)

B  5   -0.120949
   6    1.307612
   7    0.202408
   8   -0.506307
   9    0.624723
C  5    2.260423
   6    0.701160
   7    1.351438
   8   -1.288183
   9   -0.197429
dtype: float64


**48**. Tính tổng các giá trị trong `s` cho mỗi nhãn ở cấp độ đầu tiên (bạn sẽ có Series cung cấp tổng cho các nhãn A, B và C).

In [54]:
sum_by_first = s.groupby(level=0).sum()  
print(sum_by_first)

A   -1.717645
B    0.510236
C    2.041182
dtype: float64


**49**. Giả sử `sum()` (và các phương pháp khác) không chấp nhận đối số từ khóa `level`. Bạn có thể thực hiện tương đương với `s.sum(level=1)` bằng cách nào khác?

In [55]:
sum_by_second = s.unstack().sum(axis=1)
print(sum_by_second)

A   -1.717645
B    0.510236
C    2.041182
dtype: float64


**50**. Đổi các cấp độ của MultiIndex để chúng ta có một chỉ mục có dạng (chữ cái, số). Series mới này có được sắp xếp theo lexorp đúng không? Nếu không, hãy sắp xếp nó.

In [56]:
s_swapped = s.swaplevel().sort_index()
print(s_swapped)

0  A   -0.113967
   B   -0.498954
   C    0.530930
1  A   -0.699651
   B   -0.579669
   C   -2.178226
2  A   -0.811594
   B   -1.282645
   C    0.351061
3  A    0.694270
   B    1.183657
   C    0.487015
4  A   -0.645175
   B    0.180360
   C    0.022994
5  A    0.610877
   B   -0.120949
   C    2.260423
6  A    1.035288
   B    1.307612
   C    0.701160
7  A   -0.988185
   B    0.202408
   C    1.351438
8  A    0.384448
   B   -0.506307
   C   -1.288183
9  A   -1.183955
   B    0.624723
   C   -0.197429
dtype: float64
